# Generated by Django 2.2.12 on 2021-05-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoTemplateModel',
            fields=[
                ('memo_id', models.AutoField(primary_key=True, serialize=False)),
                ('memo_name', models.CharField(help_text='名称', max_length=10)),
                ('memo_time', models.DateTimeField(auto_now=True, help_text='最后修改日期', null=True)),
                ('memo_tent', models.CharField(help_text='内容', max_length=100)),
            ],
            options={
                'db_table': 'memoa',
            },
        ),
    ]
